version: '3'

volumes:
  device_management_api_local_postgres_data: {}
  device_management_api_local_postgres_data_backups: {}
  mongodb:
  mongoconfig:



services:
  django:
    build: .
    command: bash /start
    volumes:
      - .:/code
    env_file:
      - ./dev.env
    ports:
      - "8000:8000"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: celery -A device_api.celery_cfg worker --loglevel=info
    env_file:
      - ./dev.env
    depends_on:
      - redis
      - django

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: celery -A device_api.celery_cfg beat --loglevel=info
    env_file:
      - ./dev.env
    depends_on:
      - redis
      - django

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    image: device_management_api_production_postgres
    container_name: device_management_api_local_postgres
    volumes:
      - device_management_api_local_postgres_data:/var/lib/postgresql/data
      - device_management_api_local_postgres_data_backups:/backups
    env_file:
      - ./postgres/.postgres

  mongodb:
    image: mongo
    ports:
      - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password

networks:
  mongo_net:
    driver: bridge